kind: pipeline
type: docker
name: generic

steps:
  - name: generic
    image: ghcr.io/nextcloud/continuous-integration-android8:2
    commands:
      - ./gradlew --console=plain assembleGeneric

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
type: docker
name: gplay

steps:
  - name: gplay
    image: ghcr.io/nextcloud/continuous-integration-android8:2
    commands:
      - ./gradlew --console=plain assembleGplay

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: tests

steps:
  - name: all
    image: ghcr.io/nextcloud/continuous-integration-android8:2
    privileged: true
    commands:
      - emulator-headless -avd android-27 -no-snapshot -gpu swiftshader_indirect -no-window -no-audio -skin 500x833 &
      - scripts/wait_for_emulator.sh
      - ./gradlew --console=plain testGplayDebugUnitTest connectedGplayDebugAndroidTest

services:
  - name: server
    image: nextcloudci/server:server-17
    environment:
      EVAL: "true"
    commands:
      - BRANCH='stable23' /usr/local/bin/initnc.sh
      - echo 127.0.0.1 server >> /etc/hosts
      - su www-data -c "OC_PASS=user1 php /var/www/html/occ user:add --password-from-env --display-name='User One' user1"
      - su www-data -c "OC_PASS=user2 php /var/www/html/occ user:add --password-from-env --display-name='User Two' user2"
      - su www-data -c "OC_PASS=user3 php /var/www/html/occ user:add --password-from-env --display-name='User Three' user3"
      - su www-data -c "php /var/www/html/occ user:setting user2 files quota 1G"
      - su www-data -c "php /var/www/html/occ group:add users"
      - su www-data -c "php /var/www/html/occ group:adduser users user1"
      - su www-data -c "php /var/www/html/occ group:adduser users user2"
      - su www-data -c "git clone -b stable23 https://github.com/nextcloud/spreed.git /var/www/html/apps/spreed/"
      - su www-data -c "php /var/www/html/occ app:enable spreed"
      - /usr/local/bin/run.sh

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: analysis

steps:
  - name: analysis
    image: ghcr.io/nextcloud/continuous-integration-android8:2
    environment:
      GIT_USERNAME:
        from_secret: GIT_USERNAME
      GIT_TOKEN:
        from_secret: GIT_TOKEN
      LOG_USERNAME:
        from_secret: LOG_USERNAME
      LOG_PASSWORD:
        from_secret: LOG_PASSWORD
    commands:
      - export BRANCH=$(scripts/analysis/getBranchName.sh $GIT_USERNAME $GIT_TOKEN $DRONE_PULL_REQUEST)
      - scripts/analysis/analysis-wrapper.sh $GIT_USERNAME $GIT_TOKEN $BRANCH $LOG_USERNAME $LOG_PASSWORD $DRONE_BUILD_NUMBER $DRONE_PULL_REQUEST

  - name: notify
    image: drillster/drone-email
    host: $EMAIL_HOST
    port: 587
    username: $EMAIL_USERNAME
    password: $EMAIL_PASSWORD
    from: nextcloud-drone@kaminsky.me
    skip_verify: true
    recipients_only: true
    recipients: [ $EMAIL_RECIPIENTS ]
    environment:
      EMAIL_USERNAME:
        from_secret: EMAIL_USERNAME
      EMAIL_PASSWORD:
        from_secret: EMAIL_PASSWORD
      EMAIL_RECIPIENTS:
        from_secret: EMAIL_RECIPIENTS
      EMAIL_HOST:
        from_secret: EMAIL_HOST
    when:
      event:
        - push
      status:
        - failure
      branch:
        - master

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
