/*
 * Nextcloud Talk application
 *
 * @author Mario Danic
 * Copyright (C) 2017 Mario Danic
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.nextcloud.talk.utils.bundle

object BundleKeys {
    val KEY_OPEN_CONVERSATION = "KEY_OPEN_CONVERSATION"
    val KEY_SELECTED_USERS = "KEY_SELECTED_USERS"
    val KEY_SELECTED_GROUPS = "KEY_SELECTED_GROUPS"
    val KEY_USERNAME = "KEY_USERNAME"
    val KEY_TOKEN = "KEY_TOKEN"
    val KEY_BASE_URL = "KEY_BASE_URL"
    val KEY_IS_ACCOUNT_IMPORT = "KEY_IS_ACCOUNT_IMPORT"
    val KEY_ORIGINAL_PROTOCOL = "KEY_ORIGINAL_PROTOCOL"
    val KEY_ROOM = "KEY_CONVERSATION"
    val KEY_OPERATION_CODE = "KEY_OPERATION_CODE"
    val KEY_SHARE_INTENT = "KEY_SHARE_INTENT"
    val KEY_APP_ITEM_PACKAGE_NAME = "KEY_APP_ITEM_PACKAGE_NAME"
    val KEY_APP_ITEM_NAME = "KEY_APP_ITEM_NAME"
    val KEY_CONVERSATION_PASSWORD = "KEY_CONVERSATION_PASSWORD"
    val KEY_CONVERSATION_TOKEN = "KEY_CONVERSATION_TOKEN"
    val KEY_USER_ENTITY = "KEY_USER_ENTITY"
    val KEY_NEW_CONVERSATION = "KEY_NEW_CONVERSATION"
    val KEY_NEW_GROUP_CONVERSATION = "KEY_NEW_GROUP_CONVERSATION"
    val KEY_ADD_PARTICIPANTS = "KEY_ADD_PARTICIPANTS"
    val KEY_EXISTING_PARTICIPANTS = "KEY_EXISTING_PARTICIPANTS"
    val KEY_CALL_URL = "KEY_CALL_URL"
    val KEY_MODIFIED_BASE_URL = "KEY_MODIFIED_BASE_URL"
    val KEY_INTERNAL_USER_ID = "KEY_INTERNAL_USER_ID"
    val KEY_CONVERSATION_TYPE = "KEY_CONVERSATION_TYPE"
    val KEY_INVITED_PARTICIPANTS = "KEY_INVITED_PARTICIPANTS"
    val KEY_INVITED_GROUP = "KEY_INVITED_GROUP"
    val KEY_CONVERSATION_NAME = "KEY_CONVERSATION_NAME"
    val KEY_CALL_VOICE_ONLY = "KEY_CALL_VOICE_ONLY"
    val KEY_ACTIVE_CONVERSATION = "KEY_ACTIVE_CONVERSATION"
    val KEY_SERVER_CAPABILITIES = "KEY_SERVER_CAPABILITIES"
    val KEY_OPEN_INCOMING_CALL = "KEY_OPEN_INCOMING_CALL"
    val KEY_ROOM_ID = "KEY_ROOM_ID"
    val KEY_ARE_CALL_SOUNDS = "KEY_ARE_CALL_SOUNDS"
    val KEY_BROWSER_TYPE = "KEY_BROWSER_TYPE"
    val KEY_FILE_PATHS = "KEY_FILE_PATHS"
    val KEY_ACCOUNT = "KEY_ACCOUNT"
    val KEY_FILE_ID = "KEY_FILE_ID"
    val KEY_NOTIFICATION_ID = "KEY_NOTIFICATION_ID"
    val KEY_ACTIVE_NOTIFICATION = "KEY_ACTIVE_NOTIFICATION"
    val KEY_CONVERSATION_ID = "KEY_CONVERSATION_ID"

    val KEY_ENCRYPTED_SUBJECT = "KEY_ENCRYPTED_SUBJECT"
    val KEY_ENCRYPTED_SIGNATURE = "KEY_ENCRYPTED_SIGNATURE"

    val KEY_REJECT_INCOMING_CALL = "KEY_REJECT_INCOMING_CALL"
    val KEY_SHOW_INCOMING_CALL = "KEY_SHOW_INCOMING_CALL"
    val KEY_INCOMING_PUSH_MESSSAGE = "KEY_INCOMING_PUSH_MESSAGE"
    val KEY_DECRYPTED_PUSH_MESSAGE = "KEY_DECRYPTED_PUSH_MESSAGE"
    val KEY_SIGNATURE_VERIFICATION = "KEY_SIGNATURE_VERIFICATION"
}
