# This is the minimum version number required.
fastlane_version "2.58.0"

skip_docs

## public lanes

desc "Upload Alpha version to play store"
lane :uploadAlphaToPlayStore do |options|
    upload_to_play_store(
        skip_upload_images: true,
        skip_upload_aab: true,
        skip_upload_changelogs: true,
        skip_upload_metadata: true,
        track: 'alpha',
        apk: "~/apks-talk/android-talk-" + options[:version] + ".apk",
    )
end
