# SPDX-FileCopyrightText: 2018-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later


## config
# add following to your shell rc:
# export FASTLANE_TALK_UPLOAD_STORE_FILE=""
# export FASTLANE_TALK_UPLOAD_STORE_PASSWORD=""
# export FASTLANE_TALK_UPLOAD_KEY_ALIAS=""
# export FASTLANE_TALK_UPLOAD_KEY_PASSWORD=""
# export FASTLANE_NEXTCLOUD_GITHUB_API_TOKEN=""




skip_docs

APP="talk"
REPO="nextcloud/talk-android"

GRADLE_SIGNING_PROPERTIES = {
  "android.injected.signing.store.file" => ENV["FASTLANE_TALK_UPLOAD_STORE_FILE"],
  "android.injected.signing.store.password" => ENV["FASTLANE_TALK_UPLOAD_STORE_PASSWORD"],
  "android.injected.signing.key.alias" => ENV["FASTLANE_TALK_UPLOAD_KEY_ALIAS"],
  "android.injected.signing.key.password" => ENV["FASTLANE_TALK_UPLOAD_KEY_PASSWORD"],
}.freeze

import("./common.Fastfile")
