// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package com.nextcloud.talk.models.database;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;
import javax.annotation.Generated;

@Generated("io.requery.processor.EntityProcessor")
public class Models {
    public static final EntityModel DEFAULT = new EntityModelBuilder("default")
    .addType(UserEntity.$TYPE)
    .addType(ArbitraryStorageEntity.$TYPE)
    .build();

    private Models() {
    }
}
